techcare/urls.py
from django.contrib import admin
from django.urls import path
from users.views import home, user_login, user_signup, create_order, create_order_success, redirect_by_role, user_logout
from orders.views import orders_list, master_page, order_assign_master_view, order_list_view, admin_order_list_view, order_detail_view, order_update_view, create_estimate_view
from warehouse.views import WarehouseListView, WarehouseCreateView, WarehouseUpdateView, admin_page
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('redirect_by_role/', redirect_by_role, name='redirect_by_role'),
    # user
    path('', home, name='home'),
    path('orders/list/', orders_list, name='orders_list'),
    path('orders/create/', create_order, name='create_order'),
    path('orders/create/success/', create_order_success, name='create_order_success'),
    path('signup/', user_signup, name='user_signup'),
    path('login/', user_login, name='user_login'),
    path('logout/', user_logout, name='logout'),

    #admin
    path('administrator/home/', admin_page, name='admin_page'),
    path(
        'administrator/orders/',
        admin_order_list_view.as_view(),
        name='admin_orders'
    ),
    path(
        'administrator/orders/<int:pk>/assign/',
        order_assign_master_view.as_view(),
        name='order_assign_master'
    ),
    path('administrator/warehouse', WarehouseListView.as_view(), name='warehouse_list'),
    path('administrator/warehouse/add', WarehouseCreateView.as_view(), name='warehouse_add'),
    path('administrator/warehouse/<int:pk>/edit', WarehouseUpdateView.as_view(), name='warehouse_update'),
     
    #master
    path('master/home/', master_page, name='master_page'),
    path('master/order/',order_list_view.as_view(), name='master_orders'),
    path('master/order/<int:pk>/', order_detail_view.as_view(), name='master_order_detail'),
    path('master/order/<int:pk>/update', order_update_view.as_view(), name='master_order_update'),
    path('master/order/<int:pk>/estimate', create_estimate_view.as_view(), name='create_estimate'),
]

orders/models.py
from django.db import models
from users.models import User
from warehouse.models import Device, Part

class Order(models.Model):
   class OrderStatus(models.TextChoices):
      CREATED = 'created', 'Создан'
      IN_PROGRESS = 'in_progress', 'В работе'
      COMPLETED = 'completed', 'Завершен'
      CANCELLED = 'cancelled', 'Отменен'
   client = models.ForeignKey(User, on_delete=models.CASCADE,limit_choices_to={'role': User.Roles.CLIENT}, verbose_name='Клиент')
   master = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'role': User.Roles.MASTER}, verbose_name='Мастер', related_name='master_orders', null=True, blank=True)
   device = models.ForeignKey(Device, on_delete=models.CASCADE, verbose_name='Устройство')
   parts = models.ManyToManyField(Part, blank=True, verbose_name='Запчасти')
   status = models.CharField(max_length=20, choices=OrderStatus.choices, default=OrderStatus.CREATED, verbose_name='Статус')
   created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
   updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
   completed_at = models.DateTimeField(null=True, blank=True, verbose_name='Дата завершения')
   problem_description = models.TextField(verbose_name='Описание проблемы')
   @property
   def number(self):
      return f"ORD-{self.pk:05d}"
   @property
   def master_name(self):
     return self.master.fill_name if self.master else "Не назначен"
   @property
   def client_name(self):
      return self.client.fill_name
   @property
   def device_view(self):
      return f"{self.device.__str__()}"
   @property
   def device_name(self):
      return f"{self.device.number} —{self.device.full_name}"
   @property
   def parts_list(self):
      return ", ".join(part.full_name for part in self.parts.all())
   @property
   def is_completed(self):
      return self.status == self.OrderStatus.COMPLETED
   @property
   def full_name(self):
      return f"{self.number} Клиент:{self.client.fill_name} Девайс:{self.device.full_name} Мастер:{self.master_name}"
   def __str__(self):
      if self.master:
          return f"Заказ {self.number} - {self.status} {self.master.fill_name} {self.updated_at}"
      return f"Заказ {self.number} - {self.status} {self.created_at}"
class Estimate(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='estimates', verbose_name='Заявка')
    total_cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Общая стоимость', blank=True, null=True)
    parts_cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Стоимость деталей')
    labor_cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Стоимость работ')
    notes = models.TextField(blank=True, verbose_name='Заметки по смете')

    def save(self, *args, **kwargs):
        if self.total_cost is None:
            self.total_cost = (self.parts_cost or 0) + (self.labor_cost or 0)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Смета для {self.order.full_name} — {self.total_cost} руб."

warehouse/models.py
from django.db import models
from django.core.validators import RegexValidator

name_validator = RegexValidator(
    regex=r'^[A-Za-zА-Яа-яЁё0-9]+$',
    message='Разрешены только буквы и цифры'
)
class Device(models.Model):
  class DeviceType(models.TextChoices):
    PHONE = 'phone', 'Телефон'
    TABLET = 'tablet', 'Планшет'
    LAPTOP = 'laptop', 'Ноутбук'
    DESKTOP = 'desktop', 'ПК'
    OTHER = 'other', 'Другое'
  class DeviceBrand(models.TextChoices):
     APPLE = 'apple', 'Apple'
     SAMSUNG = 'samsung', 'Samsung'
     HUAWEI = 'huawei', 'Huawei'
     XIAOMI = 'xiaomi', 'Xiaomi'
     HONOR = 'honor', 'Honor'
     ASUS = 'asus', 'Asus'
     LENOVO = 'lenovo', 'Lenovo'
     MSI = 'msi', 'MSI'
     ACER = 'acer', 'Acer'
     DELL = 'dell', 'Dell'
     LG = 'lg', 'LG'
     HP = 'hp', 'HP'
     OTHER = 'other', 'Другое'
  type = models.CharField(max_length=20, choices=DeviceType.choices, verbose_name='Тип устройства')
  brand = models.CharField(max_length=20, choices=DeviceBrand.choices, verbose_name='Производитель')
  model = models.CharField(max_length=50, verbose_name='Модель',validators=[name_validator])
  @property
  def number(self):
      return f"DEV-{self.pk:05d}"
  @property
  def full_name(self):
      brand_display = dict(self.DeviceBrand.choices).get(self.brand, self.brand)
      return f"{brand_display} {self.model}"
  def __str__(self):
      type_display = dict(self.DeviceType.choices).get(self.type, self.type)
      return f"{type_display} {self.full_name}"
  def save(self, *args, **kwargs):
    self.full_clean()
    super().save(*args, **kwargs)
def validate_even(value):
  if value % 2 != 0:
      raise ValidationError(f'{value} не является чётным числом!')
class Part(models.Model):
  class PartType(models.TextChoices):
    SCREEN = 'screen', 'Экран'
    BATTERY = 'battery', 'Батарея'
    CAMERA = 'camera', 'Камера'
    KEYBOARD = 'keyboard', 'Клавиатура'
    PROCESSOR = 'processor', 'Процессор'
    RAM = 'ram', 'Оперативная память'
    STORAGE = 'storage', 'Накопитель'
    POWER_SUPPLY = 'power_supply', 'Блок питания'
    MOTHERBOARD = 'motherboard', 'Материнская плата'
    CASE = 'case', 'Корпус'
    GRAPHICS_CARD = 'graphics_card', 'Видеокарта'
    OTHER = 'other', 'Другое'
  type = models.CharField(max_length=20, choices=PartType.choices, verbose_name='Тип комплектующей')
  name = models.CharField(max_length=50, verbose_name='Название', validators=[name_validator])
  device = models.ForeignKey(Device, on_delete=models.CASCADE, verbose_name='Устройство')
  price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
  quantity = models.PositiveIntegerField(verbose_name='Количество')
  description = models.TextField(verbose_name='Описание')
  @property
  def number(self):
    return f"PART-{self.pk:05d}"
  @property
  def in_stock(self):
      return self.quantity > 0
  @property
  def stock_status(self):
      return "В наличии" if self.in_stock else "Нет в наличии"
  @property
  def full_name(self):
    return f"{self.name} {self.device.full_name}"
  def __str__(self):
    return f"{self.full_name} - {self.price} руб. (остаток: {self.quantity})"
  def save(self, *args, **kwargs):
    self.full_clean()
    super().save(*args, **kwargs)

templates/master/estimate.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Составить смету - Сервис ремонта техники{% endblock %}

{% block navigation %}
    {% include "nav/nav_master.html" %}
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<div class="form-container">
    <h2>Составить смету</h2>
    <div class="form">
        <form method="post">
        {% csrf_token %}
        {% if form.errors %}
        <ul class="errors">
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ field.label }}: {{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
        {% endif %}
        <div class="form-item">
            <label for="{{ form.parts_cost.id_for_label }}" class="form-label">{{ form.parts_cost.label}}</label>
            {{ form.parts_cost }}
        </div>
        <div class="form-item">
            <label for="{{ form.labor_cost.id_for_label }}" class="form-label">{{ form.labor_cost.label}}</label>
            {{ form.labor_cost }}
        </div>
        <div class="form-item">
            <label for="{{ form.notes.id_for_label }}" class="form-label">{{ form.notes.label}}</label>
            {{ form.notes }}
        </div>
        <button type="submit" class="btn">Сохранить изменения</button>
        </form>
        <div class="back-btn">
            <a href="{% url 'master_orders' %}" class="btn">Вернуться к списку</a>
        </div>
    </div>
</div>

{% endblock %}

templates/master/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Главная - Сервис ремонта техники{% endblock %}

{% block navigation %}
    {% include "nav/nav_master.html" %}
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/tables.css' %}">
{% endblock %}

{% block content %}
<div class="table-container">
    <h2>Добро пожаловать!</h2>
    <p>Система управления заявками на ремонт техники.</p>
    
    <div class="stats">
        <div class="stat-card">
            <p>Всего заявок</p>
            <h3>{{ total_requests }}</h3>
        </div>
        <div class="stat-card">
            <p>Новые заявки</p>
            <h3>{{ new_requests }}</h3>
        </div>
        <div class="stat-card">
            <p>В работе</p>
            <h3>{{ in_progress }}</h3>
        </div>
        <div class="stat-card">
            <p>Отменены</p>
            <h3>{{ cancelled }}</h3>
        </div>
        <div class="stat-card">
            <p>Завершено</p>
            <h3>{{ completed }}</h3>
        </div>
    </div>
    
    <h3>Последние заявки</h3>
    
    {% if orders %}
    <table>
        <thead>
            <tr>
                <th>№</th>
                <th>Устройство</th>
                <th>Статус</th>
                <th>Дата создания</th>
                <th>Дата изменения</th>
                <th>Описание</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr>
                <td>{{ order.number }}</td>
                <td>{{ order.device }}</td>
                <td>
                    <span class="status {{ req.status }}">
                        {{ order.get_status_display }}
                    </span>
                </td>
                <td>{{ order.created_at|date:"d.m.Y H:i" }}</td>
                <td>{{ order.updated_at|date:"d.m.Y H:i" }}</td>
                <td>{{ order.problem_description|truncatechars:40 }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>Заявок пока нет.</p>
    {% endif %}
</div>
{% endblock %}

templates/master/order_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Заявка #{{ order.number }} - Сервис ремонта{% endblock %}

{% block navigation %}
    {% include 'nav/nav_master.html' %}
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock %}

{% block content %}
<div class="detail-container">
    <h2>Заявка #{{ order.number }}</h2>

    <div class="detail">
        <p><strong>Статус:</strong>
            <span class="status {{ order.status }}">{{ order.get_status_display }}</span>
        </p>
        <p><strong>Дата создания:</strong> {{ order.created_at|date:"d.m.Y H:i" }}</p>
        <p><strong>Последнее обновление:</strong> {{ order.updated_at|date:"d.m.Y H:i" }}</p>
        
        <h3>Информация о клиенте</h3>
        <p><strong>Имя:</strong> {{ order.client.fill_name }}</p>
        <p><strong>Телефон:</strong> {{ order.client.phone }}</p>
    
        {% if order.client.email %}
            <p><strong>Email:</strong> {{ order.client.email }}</p>
        {% endif %}
        
        <h3>Информация об устройстве</h3>
        <p><strong>Устройство:</strong> {{ order.device.full_name }}</p>
        <p><strong>Тип:</strong> {{ order.device.get_type_display }}</p>
        <p><strong>Производитель:</strong> {{ order.device.brand }}</p>
        <p><strong>Модель:</strong> {{ order.device.model }}</p>
        
        {% if order.problem_description %}
        <h3>Описание проблемы</h3>
        <p>{{ order.problem_description }}</p>
        {% endif %}
        <div class="back-btn">
            <a href="{% url 'master_orders' %}" class="back-btn">Вернуться к списку</a>
        </div>
    </div>
    
</div>
{% endblock %}

templates/master/order_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Все заявки - Сервис ремонта техники{% endblock %}

{% block navigation %}
    {% include 'nav/nav_master.html' %}
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/tables.css' %}">
{% endblock %}

{% block content %}
<div class="table-container">
<h2>Все заявки на ремонт</h2>

{% if orders %}
<table>
    <thead>
        <tr>
            <th>№</th>
            <th>Устройство</th>
            <th>Запчасти</th>
            <th>Статус</th>
            <th>Дата создания</th>
            <th>Дата изменения</th>
            <th>Описание</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for order in orders %}
        <tr>
            <td>{{ order.number }}</td>
            <td>{{ order.device }}</td>
            <td>{{ order.parts }}</td>
            <td>
                <span class="status {{ req.status }}">
                    {{ order.get_status_display }}
                </span>
            </td>
            <td>{{ order.created_at|date:"d.m.Y H:i" }}</td>
            <td>{{ order.updated_at|date:"d.m.Y H:i" }}</td>
            <td>{{ order.problem_description|truncatechars:40 }}</td>
            <td>
                <div class="table_actions">
                    <a href="{% url 'master_order_detail' order.id %}" class="table_btn">
                        Подробнее
                    </a>
                    <a href="{% url 'master_order_update' order.id %}" class="table_btn">
                        Изменить
                    </a>
                    <a href="{% url 'create_estimate' order.id %}" class="table_btn">
                        Составить смету
                    </a>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
  {% if is_paginated %}
  <div">
      {% if page_obj.has_previous %}
      <a href="?page=1" class="page_btn">Первая</a>
      <a href="?page={{ page_obj.previous_page_number }}" class="page_btn">Предыдущая</a>
      {% endif %}

      <span>Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>

      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" class="page_btn">Следующая</a>
      <a href="?page={{ page_obj.paginator.num_pages }}" class="page_btn">Последняя</a>
      {% endif %}
  </div>
  {% endif %}
{% else %}
<p>Заявок пока нет.</p>
{% endif %}
</div>
{% endblock %}

templates/master/order_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Изменить заказ — Сервис ремонта техники{% endblock %}

{% block navigation %}
    {% include 'nav/nav_master.html' %}
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<div class="form-container">
    <h2>Изменить заказ {{ order.number }}</h2>
    <div class="form">
        <form method="post">
        {% csrf_token %}
        {% if form.errors %}
        <ul class="errors">
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ field.label }}: {{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
        {% endif %}
        <div class="form-item">
            <label>{{ form.status.label }}</label>
            {{ form.status }}
            {{ form.status.errors }}
        </div>

        <div class="form-item">
            <label>Использованные запчасти</label>

            <select name="parts" id="id_parts" multiple>
                {% for part in form.parts.field.queryset %}
                    <option value="{{ part.id }}"
                        {% if part in order.parts.all %}selected{% endif %}
                    >
                        {{ part.full_name }} (остаток: {{ part.quantity }})
                    </option>
                {% endfor %}
            </select>

            <button type="button" id="add-part-btn">Добавить ещё</button>
        </div>

        <div class="form-item">
            <label>{{ form.problem_description.label }}</label>
            {{ form.problem_description }}
            {{ form.problem_description.errors }}
        </div>
        <button type="submit" class="btn">Сохранить изменения</button>
        </form>
        <div class="back-btn">
            <a href="{% url 'master_orders' %}" class="btn">Вернуться к списку</a>
        </div>
    </div>
</div>

{% endblock %}
{% block scripts %}
<script>
document.addEventListener('DOMContentLoaded', function () {
    const addBtn = document.getElementById('add-part-btn');
    const select = document.getElementById('id_parts');

    if (addBtn && select) {
        addBtn.addEventListener('click', function () {
            select.size = select.options.length;
            select.focus();
        });
    }
});
</script>
{% endblock %}

templates/master/request_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Заявка #{{ order.number }} - Сервис ремонта{% endblock %}

{% block navigation %}
    {% include 'nav/nav_master.html' %}
{% endblock %}

{% block content %}

<h2>Заявка #{{ order.number }}</h2>

<div class="card-block">
    <p><strong>Статус:</strong>
        <span class="status {{ order.status }}">{{ order.get_status_display }}</span>
    </p>
    <p><strong>Дата создания:</strong> {{ order.created_at|date:"d.m.Y H:i" }}</p>
    <p><strong>Последнее обновление:</strong> {{ order.updated_at|date:"d.m.Y H:i" }}</p>
</div>

<h3>Информация о клиенте</h3>
<div class="card-block">
    <p><strong>Имя:</strong> {{ order.client.full_name }}</p>
    <p><strong>Телефон:</strong> {{ order.client.phone }}</p>

    {% if order.client.email %}
        <p><strong>Email:</strong> {{ order.client.email }}</p>
    {% endif %}
</div>

<h3>Информация об устройстве</h3>
<div class="card-block">
    <p><strong>Устройство:</strong> {{ order.device.full_name }}</p>
    <p><strong>Тип:</strong> {{ order.device.get_type_display }}</p>
    <p><strong>Производитель:</strong> {{ order.device.brand }}</p>
    <p><strong>Модель:</strong> {{ order.device.model }}</p>
</div>

<h3>Описание проблемы</h3>
<div class="card-block">
    <p>{{ order.problem_description }}</p>
</div>

{% if order.master %}
<h3>Информация о ремонте</h3>
<div class="card-block">
    <p><strong>Мастер:</strong> {{ order.master.full_name }}</p>

    {% if order.notes %}
        <p><strong>Примечания:</strong> {{ order.notes }}</p>
    {% endif %}
</div>
{% endif %}

<div class="back-btn">
    <a href="{% url 'master_requests' %}" class="btn">Вернуться к списку</a>
</div>

{% endblock %}

templates/master/request_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Все заявки - Сервис ремонта техники{% endblock %}

{% block navigation %}
    {% include 'nav/nav_master.html' %}
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/tables.css' %}">
{% endblock %}

{% block content %}
<h2>Все заявки на ремонт</h2>

{% if requests %}
<table>
    <thead>
        <tr>
            <th>№</th>
            <th>Клиент</th>
            <th>Телефон</th>
            <th>Устройство</th>
            <th>Статус</th>
            <th>Дата создания</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for req in requests %}
        <tr>
            <td>{{ req.id }}</td>
            <td>{{ req.client_name }}</td>
            <td>{{ req.client_phone }}</td>
            <td>{{ req.device }}</td>
            <td><span class="status {{ req.status }}">{{ req.get_status_display }}</span></td>
            <td>{{ req.created_at|date:"d.m.Y H:i" }}</td>
            <td><a href="{% url 'request_detail' req.id %}" class="btn">Подробнее</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% if is_paginated %}
<div style="margin-top: 20px;">
    {% if page_obj.has_previous %}
    <a href="?page=1" class="btn">Первая</a>
    <a href="?page={{ page_obj.previous_page_number }}" class="btn">Предыдущая</a>
    {% endif %}
    
    <span>Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
    
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}" class="btn">Следующая</a>
    <a href="?page={{ page_obj.paginator.num_pages }}" class="btn">Последняя</a>
    {% endif %}
</div>
{% endif %}

{% else %}
<p>Заявок пока нет.</p>
{% endif %}
{% endblock %}